# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme_app', '0002_auto_20171115_0241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmodel',
            name='city',
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='phno',
            field=models.BigIntegerField(max_length=1000),
        ),
    ]
