# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-03 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme_app', '0003_auto_20171115_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmodel',
            name='device',
            field=models.CharField(default='None', max_length=240),
        ),
        migrations.AlterField(
            model_name='contactmodel',
            name='phno',
            field=models.BigIntegerField(),
        ),
    ]
