# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-04 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acme_app', '0004_auto_20171203_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmodel',
            name='device',
            field=models.CharField(max_length=240),
        ),
    ]
